package com.coachingcenter.api.common.error;

public enum ErrorCode {

	VALIDATION_FAILED,
	MALFORMED_REQUEST,
	RESOURCE_NOT_FOUND,
	METHOD_NOT_ALLOWED,
	UNSUPPORTED_MEDIA_TYPE,
	UNAUTHENTICATED,
	ACCESS_DENIED,
	MASTER_ADMIN_PROTECTED,
	INVALID_CREDENTIALS,
	LOGIN_LOCKED,
	CLIENT_TYPE_REQUIRED,
	INVALID_CODE,
	CODE_EXPIRED,
	CODE_ALREADY_USED,
	CODE_ATTEMPTS_EXCEEDED,
	INVALID_REFRESH_TOKEN,
	CURRENT_PASSWORD_INVALID,
	PASSWORD_NOT_ACCEPTED,
	DUPLICATE_PHONE,
	DUPLICATE_EMAIL,
	INTERNAL_ERROR

}
